
/// Sound effects.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub enum SoundFx {
	GameOver,
	GameWin,
	TimeLow,
	Derezz,
	CantMove,
	ICCollected,
	KeyCollected,
	BootCollected,
	BootsStolen,
	Teleporting,
	LockOpened,
	SocketOpened,
	ButtonPressed,
	TileEmptied,
	WallCreated,
	BlueWallCleared,
	TrapEntered,
	BombExplosion,
	WaterSplash,
	OneShotCount,
	BlockMoving,
	SkatingForward,
	SkatingTurn,
	Sliding,
	SlideWalking,
	IceWalking,
	WaterWalking,
	FireWalking,
	WallPopup,
}
