use super::*;

pub static TILES_PLAY: [render::TileGfx; 50] = [
	render::TileGfx { sprite: data::SpriteId::Blank, model: data::ModelId::Empty }, // Terrain::Blank
	render::TileGfx { sprite: data::SpriteId::Floor, model: data::ModelId::Floor }, // Terrain::Floor
	render::TileGfx { sprite: data::SpriteId::Wall, model: data::ModelId::Wall }, // Terrain::Wall
	render::TileGfx { sprite: data::SpriteId::Floor, model: data::ModelId::Floor }, // Terrain::Socket
	render::TileGfx { sprite: data::SpriteId::BlueLock, model: data::ModelId::Wall }, // Terrain::BlueLock
	render::TileGfx { sprite: data::SpriteId::RedLock, model: data::ModelId::Wall }, // Terrain::RedLock
	render::TileGfx { sprite: data::SpriteId::GreenLock, model: data::ModelId::Wall }, // Terrain::GreenLock
	render::TileGfx { sprite: data::SpriteId::YellowLock, model: data::ModelId::Wall }, // Terrain::YellowLock
	render::TileGfx { sprite: data::SpriteId::Hint, model: data::ModelId::Floor }, // Terrain::Hint
	render::TileGfx { sprite: data::SpriteId::Exit1, model: data::ModelId::Portal }, // Terrain::Exit
	render::TileGfx { sprite: data::SpriteId::Exit1, model: data::ModelId::Portal }, // Terrain::FakeExit
	render::TileGfx { sprite: data::SpriteId::Water, model: data::ModelId::Floor }, // Terrain::Water
	render::TileGfx { sprite: data::SpriteId::WaterSplash, model: data::ModelId::Floor }, // Terrain::WaterHazard
	render::TileGfx { sprite: data::SpriteId::Floor, model: data::ModelId::Floor }, // Terrain::Fire
	render::TileGfx { sprite: data::SpriteId::Dirt, model: data::ModelId::Floor }, // Terrain::Dirt
	render::TileGfx { sprite: data::SpriteId::DirtBlock, model: data::ModelId::Wall }, // Terrain::DirtBlock
	render::TileGfx { sprite: data::SpriteId::Gravel, model: data::ModelId::Floor }, // Terrain::Gravel
	render::TileGfx { sprite: data::SpriteId::Ice, model: data::ModelId::Floor }, // Terrain::Ice
	render::TileGfx { sprite: data::SpriteId::IceCornerNW, model: data::ModelId::Floor }, // Terrain::IceNW
	render::TileGfx { sprite: data::SpriteId::IceCornerNE, model: data::ModelId::Floor }, // Terrain::IceNE
	render::TileGfx { sprite: data::SpriteId::IceCornerSW, model: data::ModelId::Floor }, // Terrain::IceSW
	render::TileGfx { sprite: data::SpriteId::IceCornerSE, model: data::ModelId::Floor }, // Terrain::IceSE
	render::TileGfx { sprite: data::SpriteId::ForceUp, model: data::ModelId::Floor }, // Terrain::ForceN
	render::TileGfx { sprite: data::SpriteId::ForceLeft, model: data::ModelId::Floor }, // Terrain::ForceW
	render::TileGfx { sprite: data::SpriteId::ForceDown, model: data::ModelId::Floor }, // Terrain::ForceS
	render::TileGfx { sprite: data::SpriteId::ForceRight, model: data::ModelId::Floor }, // Terrain::ForceE
	render::TileGfx { sprite: data::SpriteId::ForceRandom, model: data::ModelId::Floor }, // Terrain::ForceRandom
	render::TileGfx { sprite: data::SpriteId::CloneMachine, model: data::ModelId::Wall }, // Terrain::CloneMachine
	render::TileGfx { sprite: data::SpriteId::CloneBlockN, model: data::ModelId::Wall }, // Terrain::CloneBlockN
	render::TileGfx { sprite: data::SpriteId::CloneBlockW, model: data::ModelId::Wall }, // Terrain::CloneBlockW
	render::TileGfx { sprite: data::SpriteId::CloneBlockS, model: data::ModelId::Wall }, // Terrain::CloneBlockS
	render::TileGfx { sprite: data::SpriteId::CloneBlockE, model: data::ModelId::Wall }, // Terrain::CloneBlockE
	render::TileGfx { sprite: data::SpriteId::OnOffFloor, model: data::ModelId::Floor }, // Terrain::ToggleFloor
	render::TileGfx { sprite: data::SpriteId::OnOffFloor, model: data::ModelId::Floor }, // Terrain::ToggleWall
	render::TileGfx { sprite: data::SpriteId::ThinWallN, model: data::ModelId::Floor }, // Terrain::ThinWallN
	render::TileGfx { sprite: data::SpriteId::ThinWallW, model: data::ModelId::Floor }, // Terrain::ThinWallW
	render::TileGfx { sprite: data::SpriteId::ThinWallS, model: data::ModelId::Floor }, // Terrain::ThinWallS
	render::TileGfx { sprite: data::SpriteId::ThinWallE, model: data::ModelId::Floor }, // Terrain::ThinWallE
	render::TileGfx { sprite: data::SpriteId::ThinWallSE, model: data::ModelId::Floor }, // Terrain::ThinWallSE
	render::TileGfx { sprite: data::SpriteId::Floor, model: data::ModelId::Floor }, // Terrain::HiddenWall
	render::TileGfx { sprite: data::SpriteId::Floor, model: data::ModelId::Floor }, // Terrain::InvisibleWall
	render::TileGfx { sprite: data::SpriteId::BlueWall, model: data::ModelId::Wall }, // Terrain::RealBlueWall
	render::TileGfx { sprite: data::SpriteId::BlueWall, model: data::ModelId::Wall }, // Terrain::FakeBlueWall
	render::TileGfx { sprite: data::SpriteId::GreenSwitch, model: data::ModelId::Floor }, // Terrain::GreenButton
	render::TileGfx { sprite: data::SpriteId::RedSwitch, model: data::ModelId::Floor }, // Terrain::RedButton
	render::TileGfx { sprite: data::SpriteId::BrownSwitch, model: data::ModelId::Floor }, // Terrain::BrownButton
	render::TileGfx { sprite: data::SpriteId::BlueSwitch, model: data::ModelId::Floor }, // Terrain::BlueButton
	render::TileGfx { sprite: data::SpriteId::Teleport, model: data::ModelId::Floor }, // Terrain::Teleport
	render::TileGfx { sprite: data::SpriteId::BearTrap, model: data::ModelId::Floor }, // Terrain::BearTrap
	render::TileGfx { sprite: data::SpriteId::RecessedWall, model: data::ModelId::Floor }, // Terrain::RecessedWall
];
