[package]
name = "chipty"
version = "0.1.0"
edition = "2021"

[dependencies]
urandom.workspace = true
cvmath.workspace = true
serde.workspace = true
serde_json.workspace = true
flate2.workspace = true
basenc.workspace = true
