use crate::Compass;

#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Copy, Clone, Default, Debug, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub enum SpriteId {
	#[default]
	Blank,
	Floor,
	Wall,
	Chip,
	Socket,
	ExitA,
	Hint,
	WaterA,
	WaterHazard,
	DirtBlock,
	IceBlock,
	Dirt,
	Gravel,
	Fire,
	FireA,
	Ice,
	IceCornerNW,
	IceCornerNE,
	IceCornerSW,
	IceCornerSE,
	ForceFloorN,
	ForceFloorW,
	ForceFloorS,
	ForceFloorE,
	ForceRandom,
	ForceFloorNA,
	ForceFloorWA,
	ForceFloorSA,
	ForceFloorEA,
	ForceRandomA,
	CloneMachine,
	CloneBlockN,
	CloneBlockW,
	CloneBlockS,
	CloneBlockE,
	ThinWallN,
	ThinWallW,
	ThinWallS,
	ThinWallE,
	ThinWallSE,
	Flippers,
	FireBoots,
	IceSkates,
	SuctionBoots,
	PlayerCheer,
	PlayerWalkIdle,
	PlayerWalkN,
	PlayerWalkW,
	PlayerWalkS,
	PlayerWalkE,
	PlayerWalkNA,
	PlayerWalkWA,
	PlayerWalkSA,
	PlayerWalkEA,
	PlayerPushN,
	PlayerPushE,
	PlayerPushS,
	PlayerPushW,
	PlayerPushNA,
	PlayerPushEA,
	PlayerPushSA,
	PlayerPushWA,
	PlayerSwimIdle,
	PlayerSwimN,
	PlayerSwimNAlt,
	PlayerSwimW,
	PlayerSwimS,
	PlayerSwimE,
	PlayerBurned,
	WaterSplash,
	BlueKey,
	RedKey,
	GreenKey,
	YellowKey,
	BlueLock,
	RedLock,
	GreenLock,
	YellowLock,
	HiddenWall,
	InvisibleWall,
	RealBlueWall,
	FakeBlueWall,
	GreenButton,
	RedButton,
	BrownButton,
	BlueButton,
	ToggleWall,
	ToggleFloor,
	ToggleWallA,
	ToggleFloorA,
	Bomb,
	BombA,
	Thief,
	Teleport,
	BearTrap,
	BearTrapInactiveA,
	BearTrapActiveA,
	RecessedWall,
	BugN,
	BugW,
	BugS,
	BugE,
	BugNA,
	BugWA,
	BugSA,
	BugEA,
	TankN,
	TankW,
	TankS,
	TankE,
	PinkBall,
	PinkBallA,
	Fireball,
	FireballA,
	GliderN,
	GliderW,
	GliderS,
	GliderE,
	GliderNA,
	GliderWA,
	GliderSA,
	GliderEA,
	WalkerN,
	WalkerW,
	WalkerS,
	WalkerE,
	WalkerNA,
	WalkerWA,
	WalkerSA,
	WalkerEA,
	TeethN,
	TeethW,
	TeethS,
	TeethE,
	TeethNA,
	TeethWA,
	TeethSA,
	TeethEA,
	Blob,
	BlobNA,
	BlobEA,
	BlobSA,
	BlobWA,
	ParameciumN,
	ParameciumW,
	ParameciumS,
	ParameciumE,
	ParameciumNA,
	ParameciumWA,
	ParameciumSA,
	ParameciumEA,
}

impl SpriteId {
	#[inline]
	pub fn face_dir(self) -> Option<Compass> {
		match self {
			SpriteId::BugN | SpriteId::BugNA => Some(Compass::Up),
			SpriteId::BugW | SpriteId::BugWA => Some(Compass::Left),
			SpriteId::BugS | SpriteId::BugSA => Some(Compass::Down),
			SpriteId::BugE | SpriteId::BugEA => Some(Compass::Right),
			SpriteId::TankN => Some(Compass::Up),
			SpriteId::TankW => Some(Compass::Left),
			SpriteId::TankS => Some(Compass::Down),
			SpriteId::TankE => Some(Compass::Right),
			SpriteId::GliderN | SpriteId::GliderNA => Some(Compass::Up),
			SpriteId::GliderW | SpriteId::GliderWA => Some(Compass::Left),
			SpriteId::GliderS | SpriteId::GliderSA => Some(Compass::Down),
			SpriteId::GliderE | SpriteId::GliderEA => Some(Compass::Right),
			SpriteId::TeethN | SpriteId::TeethNA => Some(Compass::Up),
			SpriteId::TeethW | SpriteId::TeethWA => Some(Compass::Left),
			SpriteId::TeethS | SpriteId::TeethSA => Some(Compass::Down),
			SpriteId::TeethE | SpriteId::TeethEA => Some(Compass::Right),
			SpriteId::BlobNA => Some(Compass::Up),
			SpriteId::BlobEA => Some(Compass::Right),
			SpriteId::BlobSA => Some(Compass::Down),
			SpriteId::BlobWA => Some(Compass::Left),
			_ => None,
		}
	}
}
