[package]
name = "chipgameplay"
version = "0.1.0"
edition = "2021"

[dependencies]
urandom = "0.1"
cvmath = { git = "https://github.com/CasualX/cvmath", features=["serde", "dataview"] }
serde = { version = "1.0", features=["derive"] }
serde_json = "1.0"
