name: Build Binaries

on:
  workflow_dispatch:

jobs:
  win32:
    runs-on: windows-latest
    steps:
    - name: Checkout Sources
      uses: actions/checkout@v6

    - name: Install Toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Build Package
      run: cargo run --release -p publish -- target/publish

    - name: Upload Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: chipdx-win32
        if-no-files-found: error
        path: target/publish/**
